# Generated by Django 2.2.3 on 2019-08-05 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LOGIN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameswon', models.IntegerField(default=0)),
                ('gameslost', models.IntegerField(default=0)),
                ('gamesdrawn', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('college', models.TextField(blank=True, max_length=500)),
                ('mobile', models.IntegerField(default=0)),
                ('botpath', models.CharField(blank=True, max_length=30)),
                ('botextension', models.TextField(blank=True, max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
