# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-19 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0009_auto_20190805_1952'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LOGIN',
            new_name='Profile',
        ),
    ]
