# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-19 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0010_auto_20190819_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='college',
            field=models.TextField(default='', max_length=500),
        ),
    ]
